Ecommerce-MVC/Controllers/HomeController.cs
using Ecommerce_MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections;
using System.Diagnostics;

namespace Ecommerce_MVC.Controllers
{
    public class HomeController : Controller
    {
        
        private readonly ISession session;
        List<Product> pro = new List<Product>();
        public HomeController(IHttpContextAccessor httpContextAccessor)
        {
            session = httpContextAccessor.HttpContext.Session;
        }

        public IActionResult Index()
        {
            var email = session.GetString("username");
            if (email != null && email!= "")
            {
                try
                {
                    return View();
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error", "Customer", new { msg = ex.Message });
                }
            }
            else
            {
                return RedirectToAction("Login", "Login");
            } 
        }
        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> DisplayList(int disc)
        {
            var email = session.GetString("username");
            if (email != null && email!= "")
            {
                try
                {
                    ViewBag.disc = disc;
                    ViewBag.bnames = CategoryVM.brands;

                    return View(CategoryVM.st);
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error", "Customer", new { msg = ex.Message });
                }
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }
        public IActionResult MyCart(int disc)
        {
            try
            {
                var email = HttpContext.Session.GetString("username");
                if (email != null && email!="")
                {
                    ViewBag.disc = disc;
                    ViewBag.Cart = "Cart ";
                    ViewBag.qty = CategoryVM.Qty;
                    return View(CategoryVM.cart);
                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Customer", new { msg = ex.Message });
            }
        }
        public async Task<IActionResult> AddToCart(int id, int disc)
        {
            try
            {
                var email = HttpContext.Session.GetString("username");
                if (email != null && email!="")
                {
                    ViewBag.disc = disc;

                    List<Product> prodDetsFromAPI = new();
                    using (var httpClient = new HttpClient())
                    {
                        using (var response = await httpClient.GetAsync("https://localhost:7100/api/Products"))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            prodDetsFromAPI = JsonConvert.DeserializeObject<List<Product>>(apiResponse);
                        }
                    }
                    var item = prodDetsFromAPI.Where(x => x.Pid == id)
                        .FirstOrDefault();

                    if (!CategoryVM.Qty.ContainsKey(id))
                    {
                        CategoryVM.cart.Add(item);
                        CategoryVM.Qty.Add(id, 0);
                    }
                    else if (CategoryVM.Qty[id] == 0)
                    {
                        CategoryVM.cart.Add(item);
                    }
                    CategoryVM.Qty[id] = CategoryVM.Qty[id] + 1;
                    foreach (var xy in CategoryVM.st)
                    {
                        foreach (var z in xy.Prods) 
                        {
                            if (z.Pid == id)
                            {
                                z.InStock--;
                            }
                        }
                    }
                    pro.Add(item);
                    ViewBag.message = "Product added to Cart !";
                    return View(pro);
                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Customer", new { msg = ex.Message });
            }
        }
        public IActionResult RemoveFromCart(int id)
        {
            try
            {
                var email = HttpContext.Session.GetString("username");
                if (email != null && email!="")
                {
                    ViewBag.Rid = id;
                    var result = (from i in CategoryVM.cart
                                  where i.Pid == ViewBag.Rid
                                  select i).ToList();
                    int key1 = (from i in CategoryVM.Qty
                                where i.Key == ViewBag.Rid
                                select i.Key).FirstOrDefault();
                    foreach (var xy in CategoryVM.st)
                    {
                        foreach (var z in xy.Prods)
                        {
                            if (z.Pid == id)
                            {
                                z.InStock++;
                            }
                        }
                    }
                    if (CategoryVM.Qty[key1] == 1)
                    {
                        foreach (var item in result)
                        {
                            CategoryVM.cart.Remove(item);
                        }
                        CategoryVM.Qty[key1] = CategoryVM.Qty[key1] - 1;
                    }
                    else
                    {
                        CategoryVM.Qty[key1] = CategoryVM.Qty[key1] - 1;
                    }
                    ViewBag.qty = CategoryVM.Qty;
                    return RedirectToAction("MyCart");
                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Customer", new { msg = ex.Message });
            }
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ecommerce-MVC/Controllers/PaymentsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce_MVC.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly ISession session;
        public PaymentsController(IHttpContextAccessor httpContextAccessor)
        {
            session = httpContextAccessor.HttpContext.Session;
        }
        public IActionResult ModeOfPayment(double oid, string pids)
        {
            try
            {
                var email = session.GetString("username");
                if (email != null && email!="")
                {
                    ViewBag.oid = oid;
                    ViewBag.pids = pids;
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Customer", new { msg = ex.InnerException.Message });
            }
        }
    }
}

Ecommerce-MVC/Views/Home/AddToCart.cshtml
<div style="background-color:mintcream;padding-left:30px;padding-right:30px;padding-top:30px;padding-bottom:30px">
    @{
        @model List<Product>
        <h5>@ViewBag.message</h5>
        @foreach (var item in Model)
        {
            <div>
                <table>
                    <tr>
                        <td><img src="@item.Imglink" height="150px" width="150px" /></td>
                        <td>
                    <tr><td>Product Id: @item.Pid</td></tr>
                    <tr><td>Product Name: @item.ScType</td></tr>
                    <tr><td>Price: Rs.@item.Price</td></tr>
                    <tr><td>Size: @item.Size</td></tr>
                    </td>
                    </tr>
                </table>
            </div>
            <hr />
            <button><a style="color:black;text-decoration:none" asp-controller="Home" asp-action="DisplayList">Back to home page</a></button>
            <br />
            <br />

            <div>
                <button><a style="color:black;text-decoration:none" asp-route-disc="@ViewBag.disc" asp-action="MyCart">View Cart </a></button>
            </div>
        }
    }
</div>

Ecommerce-MVC/Views/Home/DisplayList.cshtml
@*@model IEnumerable<ECommerceMVC.Models.Product>

*@
<div style="background-color:mintcream;padding-left:30px;padding-right:30px;padding-top:30px;padding-bottom:30px">

    @model IEnumerable<Ecommerce_MVC.Models.CategoryVM>
    <table class="table">
        @for (int item = 0; item < CategoryVM.st.Count(); item++)
        {
            var l2 = ViewBag.bnames;
            <tr>
                <th style="font-weight:40px"> @CategoryVM.st[item].Category</th>
                @for (int it = 0; it < CategoryVM.st[item].Prods.Count(); it++)
                {
                    if (@CategoryVM.st[item].Prods[it].InStock > 0)
                    {
                        ViewBag.Stock = "Available";
                    }
                    else
                    {
                        ViewBag.Stock = "Unavailable";
                    }
                <tr>

                    <td> @CategoryVM.st[item].Prods[it].SubCategory</td>
                    <td><img width="200px" height="200px" src="@CategoryVM.st[item].Prods[it].Imglink" /></td>
                    <td> @CategoryVM.st[item].Prods[it].ScType</td>
                    <td> @CategoryVM.st[item].Prods[it].Size</td>
                    <td> Rs.@CategoryVM.st[item].Prods[it].Price</td>
                    <td> @ViewBag.Stock</td>
                    <td>@l2[item][it]</td>
                    <td>
                            @if (@CategoryVM.st[item].Prods[it].InStock > 0)
                            {
                            <a asp-action="AddToCart" asp-route-disc="@ViewBag.disc" asp-route-id="@CategoryVM.st[item].Prods[it].Pid ">Add To Cart</a>
                            }
                            else
                            {
                            <p style="color:gray">Out Of order</p>
                            }
                    </td>
                </tr>
                }
            </tr>
        }
    </table>
</div>

Ecommerce-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body style="z-index:1">
    <div style="background-color:mintcream;padding-left:30px;width:100%;padding-right:30px;padding-top:30px;padding-bottom:30px">

        <h5 style="font-family:'Comic Sans MS';font-size:30px;color:slategray;text-decoration:wavy"> New collection</h5>
        <div>

            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                    <li data-target="#myCarousel" data-slide-to="3"></li>
                    <li data-target="#myCarousel" data-slide-to="4"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <a asp-action="DisplayList" asp-route-disc="60"><img src="~/images/car4.jpg" alt="Image 1" style="width:100%;height:500px"></a>
                    </div>

                    <div class="item">
                        <a asp-action="DisplayList"> <img src="~/images/car1.jpg" alt="Los Angeles" style="width:100%;height:500px"></a>
                    </div>

                    <div class="item">
                        <a asp-action="DisplayList"><img src="~/images/car2.jpg" alt="Los Angeles" style="width:100%;height:500px"></a>
                    </div>
                    <div class="item">
                        <a asp-action="DisplayList">  <img src="~/images/car4.jpg" alt="Los Angeles" style="width:100%;height:500px"></a>
                    </div>
                    <div class="item">
                        <a asp-action="DisplayList"><img src="~/images/car3.jpg" alt="Los Angeles" style="width:100%;height:500px"></a>
                    </div>
                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>

</body>

Ecommerce-MVC/Views/Home/MyCart.cshtml
<div style="background-color:mintcream;padding-left:30px;padding-right:30px;padding-top:30px;padding-bottom:30px">
    @{

        @model List<Product>
        
        <h2>@ViewBag.Cart</h2>
        <hr />
        List<string> l1 = new List<string>();
        List<int> l2 = new List<int>();
        List<int> l0 = new List<int>();
        List<double> l3 = new List<double>();
        double count = 0;

        foreach (var item in Model)
        {
            <p style="float:left;padding-right:30px"><img width="100px" height="100px" src="@item.Imglink" /></p>
            <P style="float:left">Product: #@item.Pid &nbsp;</P>
            <p> @item.ScType</p>
            <p>@item.Brand.BrandName</p>
            <p>Rs.@item.Price</p>
            <p>Quantity: @ViewBag.qty[item.Pid]</p>

            l1.Add(item.ScType);
            l0.Add(item.Pid);
            l2.Add(@ViewBag.qty[item.Pid]);
            count = count + Convert.ToDouble(@item.Price) * (@ViewBag.qty[item.Pid]);
            l3.Add(Convert.ToDouble(@item.Price) * (@ViewBag.qty[item.Pid]));

            <a asp-controller="Home" asp-action="RemoveFromCart" asp-route-id="@item.Pid">Remove</a>
            <hr />
        }

        int k = l1.Count() - 1;
        string pids = "";
        @while (k >= 0)
        {
            pids = pids + Convert.ToString(l0[k]) + ";";
            k--;
        }
        @if (CategoryVM.cart.Count != 0)
        {

            <table border="1" cellpadding="10" cellspacing="5">
                <h5>Cart Subtotal</h5>
                @for (int j = 0; j < @Model.Count(); j++)
                {
                    <tr>
                        <td>@l1[j]&nbsp;</td>
                        <td>x @l2[j]&nbsp;</td>
                        <td>Rs.@l3[j]</td>
                    </tr>
                }
                <hr>
                <tr>
                <tr>
                    <td>Taxes and Delivery</td>
                    <td></td>
                    <td>Rs.67.5</td>
                </tr>
                    @if (count > 500)
                    {
                        count = count * 0.4;
                        count = count + 67.5;
                    <td>
                        Discount
                    </td>
                    <td></td>
                    <td> - @ViewBag.disc %</td>
                    }
                    else
                    {
                    <tr>
                        <td>
                            Discount
                        </td>
                        <td></td>
                        <td> - 0%</td>
                        <p style="color:red">Offer valid on min Rs 500</p>
                    </tr>
                        count = @count + 67.5;
                    }
                </tr>


                <tr>
                    <th style="text-align:right;">Total: Rs.@count</th>
                </tr>

            </table>

            <br />
            <button style="color:cornflowerblue;width:100px;height:50px"><a style="color:black;text-decoration:none" asp-controller="Payments" asp-action="ModeOfPayment" asp-route-pids="@pids" asp-route-oid="@count">Checkout </a></button>
        }
        else
        {
            <h6>Cart is empty</h6>
            <p>Add Products to cart</p>
        }
        <br>

        <br>
        <button><a style="color:black;text-decoration:none" asp-route-disc="60" asp-action="DisplayList">Back to home page</a></button>
        <br />
    }
</div>